spring.application.name=serv

spring.datasource.url=jdbc:postgresql://localhost:5432/service_hub
spring.datasource.username=postgres
spring.datasource.password=sakti

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
